# Generated by Django 2.2.4 on 2019-11-07 13:23

import Account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Concours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=Account.models.uid, max_length=32, unique=True, verbose_name='ID Utilisateur')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Téléphone')),
                ('avatar', models.TextField(verbose_name='Photo')),
                ('bdate', models.DateField(verbose_name='Date de naissance')),
                ('role', models.CharField(choices=[('P', 'Parent'), ('E', 'Enfant')], default='E', max_length=10, verbose_name='Role')),
                ('diplome', models.ManyToManyField(to='Concours.APOSDiplome')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Data',
                'verbose_name_plural': 'User Data',
                'db_table': 'apos_user',
            },
        ),
    ]
